version: '3.8'

services:
  nuxtapp:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
